# Generated by Django 3.2.3 on 2026-04-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_seed_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cats/'),
        ),
    ]
