# Generated by Django 3.2.3 on 2026-04-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_auto_20260428_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='color',
            field=models.CharField(choices=[('Gray', 'Серый'), ('Black', 'Чёрный'), ('White', 'Белый'), ('Ginger', 'Рыжий'), ('Mixed', 'Смешанный'), ('Tabby', 'Полосатый'), ('Calico', 'Трёхцветный'), ('Cream', 'Кремовый'), ('Blue', 'Голубой'), ('Fawn', 'Палевый')], max_length=16),
        ),
    ]
