# Generated by Django 3.2.3 on 2026-05-03 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cats', '0006_seed_ownership_statuses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownershipstatus',
            options={'verbose_name': 'Ownership status', 'verbose_name_plural': 'Ownership statuses'},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_personal', models.BooleanField(default=False)),
                ('consent_personal_date', models.DateTimeField(blank=True, null=True)),
                ('consent_photo', models.BooleanField(default=False)),
                ('consent_photo_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
